[package]
name = "gitcall-rust-app"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "^0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3.17"
serde_derive = "1.0"
jsonrpc-http-server = "14.2.0"
jsonrpc-core = "14.2.0"    

